// app/api/funfact/route.ts
import { NextRequest } from 'next/server';

const facts = [
  "I’ve jet skiied across Lake Michigan",
  "I played back up scrum half for an Ivy League champion rugby team",
  "I started a college newspaper called the Penn Indy.",
  "I published a book and have been interviewed on CSPAN.",
  "I’ve performed music in Japan.",
  "Rachel Maddow talked about my reporting on North Kore.",
  "Wolf Blizter yapped about my blog on CNN.",
  "I drove a $25,000 Nieman Marcus cupcake car for journalistic purposes",
  "I was once named a volunteer of the year in a small town",
  "I’ve serve on nonprofit committees and have served many nonprofits in various board roles over the years",
  "I have degrees in decision making, communication and dispute resolution.",
  "I was once brainwashed by the Koch brothers in West Virginia.",
  "I’ve embedded with the Air Force for an earthquake response mission to Mexico (and cloud surfed the cockpit of a C10).",
  "I’ve drank with Mark Zuckerberg on a roof in Palo Alto.",
  "I’ve published magazine articles, videos, music albums, NFT art, photos, newspaper articles and opinion editorials.",
  "I’ve been featured in New York Times Magazine.",
  "I reported politics for the Wall Street Journal.",
  "My sausage fingers have been humbled while shaking the hands of Shaq.",
  "The guy from Twilight once told me he liked my leather jacket.",
  "I’ve studied flower arranging in Japan.",
  "I’ve enjoyed a green tea ceremony with a geisha.",
  "I smoked weed before I met the president in the West Wing",
  "I’ve worked professionally in local journalism, political journalism, luxury journalism, financial journalism, celebrity journalism, food journalism, agricultural journalism, business journalism, documentaries and hard news.",
  "WSJ published three of my editorials as its unsigned opinion.",
  "I can spin a plate on my finger, for hours.",
  "I pet Grumpy Cat.",
  "I was once a food space engineer (bag boy).",
  "I landed my first job when I was 12 and started my working career on my 13th birthday.",
  "I’ve sold skis in the summertime.",
  "I lived down the street from the Seinfeld cafe.",
  "I’ve lived in or near several major cities: Oklahoma City, Dallas, Chicago, Detroit, Milwaukee, Philadelphia, DC, New York and San Francisco.",
  "My dad and grandma were born in California but lived in Oklahoma; I was born in Oklahoma and live in California.",
  "My fraternity’s primary hazing was forcing us to listen to Purple Rain.",
  "My keg stand record stood for years in my college fraternity.",
  "I squeezed onto Editors & Publisher’s best publishers under 35 list at age 35.",
  "I’ve done study abroads in: DC, Chiba, Japan;  Barcelona, Spain; Prague, Czech Republic",
  "I’ve formally studied Latin, Japanese, Czech, Spanish, Catalan and French.",
  "I was once a level 1 women’s rugby referee.",
  "The Project Manager Institute certified me as an agile scrum practitioner.",
  "I once walked a hundred New York City blocks to get to work during a hurricane.",
  "My desk was once above the hole left by 9/11, one building over.",
  "I got my boaters license at age 13.",
  "I’ve catered over a dozen weddings.",
  "I have skinny dipped in 7 lakes in one day.",
  "I have sold frog legs on the side of the road.",
  "I have sled down a sand dune on a mattress.",
  "I once held a Beer Olympics.",
  "I was once a fraternity pledge master.",
  "I’ve been a photographer inside two of California’s five biggest-ever wildfires",
  "I’ve eaten most of the famous cheesesteaks of Philadelphia.",
  "I’ve seen the dying lion in Lucerne.",
  "I own a rare letter between William Randolph Hearst and his mistress.",
  "I can pick a lock in a half dozen ways.",
  "I can break out of handcuffs.",
  "I can calm an angry person in 90 seconds.",
  "I’ve shot an arrow with another arrow.",
  "I have a picture of Kanye West and Taylor Swift signed by Kanye West.",
  "I have the a collection of the whole first year of Adbusters magazine.",
  "I have a collection of comics that includes complete series for DMZ, Y! The Last Man, Preacher and Transmetropolitan.",
  "I have published major websites and mobile apps serving as many as 150 million people a month.",
  "I have been part of teams that won webbie awards for Business news and CRM systems.",
  "I’ve worked for and studied under a Peabody award winning documentarian in a famous media district of Dumbo, Brooklyn.",
  "I’ve played Texas holdem poker with people who swim with sharks.",
  "I’ve swam across a lake.",
  "I’ve been paid to smoke and review cigars.",
  "I’ve picked stocks for Forbes magazine.",
  "I’ve had a story on the cover of Forbes.",
  "I’ve interviewed the Winklevoss brothers.",
  "I’ve spent over an hour in a closed room with Rudy Giuliani.",
  "I’ve been in U.S. Treasury meetings.",
  "I was expelled from the University of California, but never attended the University of California.",
  "I protested the Iraq War.",
  "I started a peer mediation club in High School.",
  "I was a freelance music promoter in high school.",
  "I once did a favor for John Mayer and worked his merch booth at a concert.",
  "I’m a high school state championship (losing) ski racer.",
  "I shared a Condé Nast lunch room with Vogue staffers.",
  "I’ve was the fill-in Letters editor for the WSJ and laid out (in newsprint) all the letters of opposition on the day when Rupert Murdoch bought it.",
  "I was intern at reason magazine under David Weigel, rockabilly expert and arguably the best political reporter of all time.",
  "I pitched the idea and became part of a team at Stanford to ran a negotiation psychology experiment modeled on Cyrano de Bergerac.",
  "I started smoking just to hang out with Bret Stephens (now the token conservative opinion columnist at the New York Times).",
  "I’ve backpacked through much of Europe.",
  "@MerriamWebster follows me on Twitter.",
  "I’ve skiied black diamonds at some of the biggest mountains in America.",
  "I gave a speech at my high school graduation.",
  "In high school I was a DARE role model",
  "I helped build a small playground.",
  "I’ve painted a hundred foot wide United States map.",
  "I’ve milled my own wood.",
  "I am an amateur locksmith.",
  "I’ve studied free market economics in a post-Soviet state.",
  "I’ve studied formal logic, decision theory and specialized in game theory.",
  "I am a certified life coach.",
  "I have certifications in Cognitive Behavior Theory, Meditation and Breathing.",
  "I’ve been a teacher and taught teachers to teach.",
  "I’ve been in hundreds of negotiations.",
  "I have been a Malibu beach professor.",
  "I’ve studied conflict resolution at the LAPD.",
  "I’m a trained divorce mediator.",
  "I practice legerdemain for stress relief.",
  "I once took the LSAT for fun.",
  "I wrote about the student union for the Stanford Daily.",
  "I studied computer science at Stanford.",
  "I taught a coding lab for journalists at Stanford.",
  "I co-hosted a political talk show on the college cable channel.",
  "In middle school, I had a radio show on the high school radio station.",
  "One of my biggest influences as a youth was a man named Dick Sachs (my high school ski coach).",
  "I’ve been a camp counselor.",
  "In Canada, I ate a bear’s leftovers.",
  "I’ve partied in subzero temperatures at a snowsuit rave in Montreal.",
  "I lost my wallet in Frankfurt and hitchhiked my way to Amsterdam.",
  "I’ve sled down a sand dune on a mattress.",
  "I’ve made my own silver jewelry.",
  "Growing up, I won dozens of awards at summer camp for my cleanliness leadership.",
  "I’ve produced and published more than a half dozen electronic music albums.",
  "I’ve published poetry.",
  "I once had a source inside Anonymous.",
  "I nicknamed a famous hacker.",
  "I’ve been targeted for hacks at information security conferences.",
  "I’ve chilled with Moxie Marlinspike, one of the modern era’s greatest cryptographers.",
  "I’ve interviewed Kevin Mitnik.",
  "I’ve endangered my life to interview Marc Andreessen.",
  "I led a multi-year investigation of “the prince of spam” that ended up being too spicy to publish.",
  "I’ve been a fact-checker.",
  "I’ve been legally threatened by a billionaire.",
  "I’ve been threatened by a police chief.",
  "I’ve been part of a kindergarten suplemental reading program.",
  "I’ve been, once simultaneously, a Rotarian and a Soroptomist (“Soroptomister”).",
  "I’ve run a 10K while wearing a gorilla mask.",
  "I’ve been featured as a float in a parade.",
  "I’ve run the music at a fireworks show.",
  "I’ve parked hundreds of cars for charity purposes.",
  "I’ve raised thousands of pounds of clothing donations.",
  "I’ve orchestrated a garbage pickup contest that removed hundreds of pounds of garbage from a local creek.",
  "I’ve run multiple free outdoor Disney movie theater experiences for local kids.",
  "I’ve delivered thousands of newspapers by hand.",
  "I’ve published hundreds of thousands of magazines.",
  "I’ve been an engineer behind the nations second largest news site.",
  "I helped digitally transform (and sell) a website for the world’s most circulated magazine.",
  "I’ve made the chief executive of a major microchip company sweat during an interview.",
  "I’ve watched a hockey game from the owner’s box.",
  "I’ve skated on the ice of Joe Louis Arena.",
  "I’ve almost drowned in an underwater cave.",
  "One of my childhood best friends became an underground acid music DJ.",
  "My childhood best friend is now a scientist that designs video games for chimpanzees.",
  "I’ve seen Deep Purple play Smoke on the Water from the front row.",
  "Radiohead was the opening act for my first concert.",
  "I was once arrested for a misdemeanor in the parking lot of a Dave Matthews Band concert.",
  "The police once detained me in front of my house and confiscated hundreds of roles of toilet paper.",
  "I gave up a rent-controlled Manhattan apartment with easy access to transit.",
  "I’ve moved back and forth between SF and NYC five times for various media gigs at Condé Nast and Forbes.",
  "I’ve eaten at a hidden underground restaurant.",
  "I’ve been a corporate IT guy and had servers held hostage for crypto.",
  "I run an at-home datacenter with several servers.",
  "I created the first WSJ and Forbes accounts on Twitter.",
  "I was a major player in a crypto horse racing game.",
  "My dad bred, raised and raced thoroughbred horses.",
  "My great-great grandfather was chairman of General Mills.",
  "One of my relatives reversed the flow of the Chicago River as sanitation czar, went on to a success political career, and was eventually mourned by several presidents.",
  "My grandfather sold ad space for Super Bowl commercials.",
  "My grandfather swept the floors at the first ever televised debate (between Nixon and Kennedy).",
  "My dad started as a stock boy at Target and died a chief executive for a major retail chain.",
  "My dad helped invent the Dollar General merchandising and store model that is ravaging small town America.",
  "I once started the day in Philly, spent a night out in New York, and woke up in Baltimore.",
  "I once went out drinking with a rugby team in Dublin and woke up in Paris.",
  "I’ve helped raise over an $100,000 for fire relief.",
  "I was president of my Rotary club.",
  "I was locally elected as a judge of elections and ran a polling location in West Philadelphia during a presidential election year.",
  "I am a professional computer programmer working in several programming languages.",
  "I’ve contributed to open source projects at Amazon and Google.",
  "I’m a contributor to two different graph database technologies.",
  "I am a skilled lock picker who can pop most Masterlocks in seconds.",
  "I have over 500 subscribers and a million views on YouTube.",
  "In the Catalonian countryside, I slept in a bed that was older than the United States.",
  "My host family in Spain was part of a clutch of Catalonian revolutionaries.",
  "I’ve been to a multi day techno rave in the Hungarian countryside.",
  "I’ve been to German house parties.",
  "I once had a race horse named Flat Tax.",
  "I have a degree in philosophy and focused on ethics.",
  "I once wrote a 27 page graduate paper about the role of smell in emotional regulation.",
  "I wrote my first breakup song in second grade and can still sing the refrain.",
  "Had dinner with Yoshitomo Nara at a Steven Starr restaurant and gave him some of my drawings.",
  "Designed a sweatshirt and sold a handful of designed t-shirts.",
  "As a child was once a model for a paper placeholder photo that came inside a picture frame.",
  "Midwest high-school ski team trained on a converted garbage dump.",
  "High school rugby coach was also the school librarian.",
  "Certified scuba diver.",
  "Worked at a Thai restaurant as a waterboy in high school.",
  "Worked the register at a Greek food restaurant in college.",
  "Sold advertising and orchestrated digital marketing campaigns.",
  "Ran a white/labeled digital ticketing event platform.",
  "Launched and operated e-commerce boutiques that sold on Instagram, Amazon and EBay.",
  "Fundraised for a senior center.",
  "Participated in multiple creek restoration and native planting projects.",
  "Was the publisher of local newspapers.",
  "Served local business across multiple towns as a board member of a Chamber of Commerce and downtown business association.",
  "Offered professional, boutique mediation services for more than four years.",
  "Three years of graduate teaching experience coaching LLM students.",
  "Eight years of corporate experience as a Chief Technology Officer.",
  "Hands-on programming career spanning decades, starting at the bottom, from developer to senior engineer to development manager to director.",
  "Published first website, a Sarah Michelle Geller fan site, in 6th grade.",
  "Launched first digital business (celebpages.com), in seventh grade, in 1998.",
  "Partitioned my first hard drive and booted first (Red Hat) Linux in 4th grade.",
  "Wrote first computer program (in AppleScript) in 3rd grade.",
  "Got into Penn on early admission.",
  "Granted a merit scholarship at Stanford to cover the majority of tuition.",
  "Enjoyed a scholarship to study at Pepperdine’s Caruso School of Law.",
  "Studied under an acolyte of Ken Cloke, the renowned mediator and conflict specialist.",
  "Sat at the negotiation table in a JAMS arbitration office.",
  "Took a class on apologies, specifically.",
  "Got special disposition from Pepperdine law dean to study extra law specialities: legal writing, organization law, employment law, contract law and torts.",
  "I had national security clearance.",
  "I interned at the White House.",
  "I have a collection of rare linksys WRT54G routers.",
  "I have a complete collection of the work that Alexander Tapéis published in Derrière le Mirroir",
  "I have a print signed by Rockwell Kent",
  "I’ve shot tens of thousands of photos with a real camera.",
  "I’ve exposed and developed film in a black room.",
  "I’ve built a treehouse.",
  "I’ve roofed a shack.",
  "I’ve floored a house.",
  "I’ve tiled a bathroom.",
  "A jail once accidentally let my brother’s murderer out of jail.",
  "Males in my family tend to die in red trucks.",
  "I’ve visited most islands in the Caribbean.",
  "I’ve never been to Disney World.",
  "I fell face first on a hiking stick in the Canadian wilderness that resulted in one dimple.",
  "Studied art history with a focus on Christian iconography.",
  "Amateur paper historian.",
  "Once had a ranch horse named Ghost — it was brown with white socks.",
  "Grew up exclusively with golden retrievers: Foxy, Treasure, Blizzard, Storm and Rain",
  "Allergic to cats — and had a cat anyways.",
  "I named my cat “Haskell” after a beautiful but ha Western rd-to-grasp functional programming language.",
  "I lived in the Chicago suburbs during the height of the Chicago Bulls.",
  "I lived in Detroit suburbs during the height of the Detroit Red Wings.",
  "Anna Kornakova dated the guy who lived across the street from me in middle school.",
  "I memorized most of the major guitar chords.",
  "I have mastered, and have now completely forgotten, Morse code."
];

export async function GET() {
  try {
    
    const randomFact = facts[Math.floor(Math.random() * facts.length)];

    return new Response(JSON.stringify({ fact: randomFact }), {
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-store',
      },
    });
  } catch (error) {
    console.error('Failed to fetch fun fact:', error);
    return new Response(
      JSON.stringify({ error: 'Failed to fetch fun fact' }),
      { status: 500 }
    );
  }
}
